Mão na massa

In [2]:
import numpy as np
import pandas as pd

In [3]:
#Exercício 1
np.random.seed(2)
E1=np.random.randint(0,100,(10))
print(E1)
print(E1.dtype)

[40 15 72 22 43 82 75  7 34 49]
int32


In [6]:
#Exercício 2
np.random.seed(2)
E2=np.random.rand(5,5)
print(E2)
print('Máximo: ',E2.max())
print('Mínimo: ',E2.min())
print('Média: ',E2.mean())

[[0.4359949  0.02592623 0.54966248 0.43532239 0.4203678 ]
 [0.33033482 0.20464863 0.61927097 0.29965467 0.26682728]
 [0.62113383 0.52914209 0.13457995 0.51357812 0.18443987]
 [0.78533515 0.85397529 0.49423684 0.84656149 0.07964548]
 [0.50524609 0.0652865  0.42812233 0.09653092 0.12715997]]
Máximo:  0.8539752926394888
Mínimo:  0.025926231827891333
Média:  0.39411936342802206


In [7]:
int()
float()
str()
list()

0

In [13]:
#Exercício 3
np.random.seed(2)
E3=np.random.rand(10)
print(E3)
print(E3.dtype)

E3_1=(E3*10).astype(int)
print(E3_1.dtype)
E3_1

<U32


array(['4.359949021420038', '0.25926231827891333', '5.496624778787091',
       '4.3532239261827685', '4.20367802087489', '3.3033482100387412',
       '2.046486340378425', '6.192709663506637', '2.9965467367452314',
       '2.6682727510286663'], dtype='<U32')

In [14]:
#Exercício 4
np.random.seed(2)
E4=np.random.randint(0,9,(3,3))
print(E4)
E4[1,:]=-1
print(E4)


[[8 8 6]
 [2 8 7]
 [2 1 5]]
[[ 8  8  6]
 [-1 -1 -1]
 [ 2  1  5]]


In [15]:
#Exercício 5 - forma 1
pd.DataFrame([['Banana', 7.90, 12],['Maça', 10.20, 3],['Pera', 11.80, 4]], columns=['fruta', 'preco', 'quantitade'])

fruta  preco  quantitade
0  Banana    7.9          12
1    Maça   10.2           3
2    Pera   11.8           4

In [19]:
#Exercício 5 - forma 2
df=pd.DataFrame()
df['fruta'] = ['Banana', 'Maça', 'Pera']
df['preco'] = [7.90, 10.20, 11.80]
df['quantidade'] = [12, 3, 4]
df

fruta  preco  quantidade
0  Banana    7.9          12
1    Maça   10.2           3
2    Pera   11.8           4