Mão na massa

In [1]:
import numpy as np
import pandas as pd

In [9]:
#Exercício 1
np.random.seed(2)
E1=np.random.randint(0,100,(10))
print(E1)
print(E1.dtype)

[40 15 72 22 43 82 75  7 34 49]
int32


In [13]:
#Exercício 2
np.random.seed(2)
E2=np.random.rand(5,5)
print('Máximo: ',E2.max())
print('Mínimo: ',E2.min())
print('Média: ',E2.mean())

Máximo:  0.8539752926394888
Mínimo:  0.025926231827891333
Média:  0.39411936342802206


In [20]:
#Exercício 3
np.random.seed(2)
E3=np.random.rand(10)
E3_1=(E3*10).astype(int)
print(E3_1.dtype)
E3_1

int32


array([4, 0, 5, 4, 4, 3, 2, 6, 2, 2])

In [26]:
#Exercício 4
np.random.seed(2)
E4=np.random.randint(0,9,(3,3))
print(E4)
E4[1,:]=-1
print(E4)


[[8 8 6]
 [2 8 7]
 [2 1 5]]
[[ 8  8  6]
 [-1 -1 -1]
 [ 2  1  5]]


In [29]:
#Exercício 5 - forma 1
pd.DataFrame([['Banana', 7.90, 12],['Maça', 10.20, 3],['Pera', 11.80, 4]], columns=['fruta', 'preco', 'quantitade'])

fruta  preco  quantitade
0  Banana    7.9          12
1    Maça   10.2           3
2    Pera   11.8           4

In [31]:
#Exercício 5 - forma 2
df=pd.DataFrame()
df['fruta'] = ['Banana', 'Maça', 'Pera']
df['preco'] = [7.90, 10.20, 11.80]
df['quantidade'] = [12, 3, 4]
df

fruta  preco  quantidade
0  Banana    7.9          12
1    Maça   10.2           3
2    Pera   11.8           4