Introdução ao NUMPY

In [ ]:
# pip install numpy

In [4]:
##Importação
import numpy as np

In [9]:
##Arrays - construção
#escalar
print('Escalar\n',5,'\n')

#vetor linha
print('Vetor linha\n', np.array([1,2,3]),'\n')

#vetor coluna
print('Vetor coluna\n', np.array([[1,2,3]]),'\n')

#matriz
print('Matriz\n', np.array([[1,2,3],[4,5,6]]), '\n')

#tensor
print('Tensor\n', np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]))


Escalar
 5 

Vetor linha
 [1 2 3] 

Vetor coluna
 [[1 2 3]] 

Matriz
 [[1 2 3]
 [4 5 6]] 

Tensor
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [18]:
##Arrays - atributos
#dtype
array_matriz_1=np.array([[1,2,3],[4,5,6]])
print('Tipo matriz 1: ',array_matriz_1.dtype)
array_matriz_2=np.array([[1.0,2,3,4],[4,5,6,4],[10,8,4,20]])
print('Tipo matriz 2: ',array_matriz_2.dtype)
#shape
print('dimensão matriz 1: ',array_matriz_1.shape)
print('dimensão matriz 2: ',array_matriz_2.shape)

Tipo matriz 1:  int32
Tipo matriz 2:  float64
dimensão matriz 1:  (2, 3)
dimensão matriz 2:  (3, 4)


In [81]:
type(array_matriz_1)

numpy.ndarray

In [22]:
##Arrays - construção padronizada
#arrays de uns
print('arrays de uns\n', np.ones((3,3)), '\n')

#arrays de zeros
print('arrays de zeros\n', np.zeros((5,2)), '\n')

#arrays com números identicos
print('arrays de valores identicos\n', np.full((2,10),51), '\n')


arrays de uns
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

arrays de zeros
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]] 

arrays de valores identicos
 [[51 51 51 51 51 51 51 51 51 51]
 [51 51 51 51 51 51 51 51 51 51]] 



In [80]:
##Arrays - aleatórios
#Rand
print(np.random.rand(2,3).round(3))
#Randint
np.random.randint(0,10,(3,3))

[[0.416 0.058 0.12 ]
 [0.629 0.129 0.172]]


array([[3, 3, 1],
       [6, 6, 7],
       [6, 7, 1]])

In [90]:
##Arrays - indexação
np.random.seed(2)
matriz=np.random.randint(0,100,(4,4))
matriz

array([[40, 15, 72, 22],
       [43, 82, 75,  7],
       [34, 49, 95, 75],
       [85, 47, 63, 31]])

In [110]:
matriz[:,0]

array([40, 43, 34, 85])

In [109]:
##Arrays - operações
np.linalg.det(matriz)

14325545.999999972

In [111]:
matriz

array([[40, 15, 72, 22],
       [43, 82, 75,  7],
       [34, 49, 95, 75],
       [85, 47, 63, 31]])

In [117]:
##Arrays - Where
teste=np.where(matriz<40, 'reprovado', 
               np.where(matriz<60, 'recuperação','Aprovado' ))
teste

array([['recuperação', 'reprovado', 'Aprovado', 'reprovado'],
       ['recuperação', 'Aprovado', 'Aprovado', 'reprovado'],
       ['reprovado', 'recuperação', 'Aprovado', 'Aprovado'],
       ['Aprovado', 'recuperação', 'Aprovado', 'reprovado']], dtype='<U11')

Introdução ao Pandas

In [ ]:
# pip install pandas

In [119]:
import pandas as pd

In [122]:
#Tipo Series
pd.Series(np.array([1,2,3]))

0    1
1    2
2    3
dtype: int32

In [124]:
#Tipo DataFrame
pd.DataFrame(matriz, columns=['portugues', 'matematica', 'ciencias', 'geografia'])

portugues  matematica  ciencias  geografia
0         40          15        72         22
1         43          82        75          7
2         34          49        95         75
3         85          47        63         31